---
title: "Supporting information for Hasegawa et al."
author: "Shun Hasegawa"
output: github_document
---

This repository stores R scripts to reproduce the results presented in the manuscript below. The raw data are available in supporting information (Tables S2-S5).

* Article title: Elevated CO~2~ concentrations reduce C~4~ abundance and decrease diversity of understorey plant community in a grassy-*Eucalyptus* woodland
* Authors: Shun Hasegawa, Juan Piñeiro, Raúl Ochoa-Hueso, Kirk L. Barnett, Anthony M. Haigh, Paul D. Rymer, Sally A. Power
* Article acceptance date:

## File description

### R scripts
* **analysis.R**: This loads required packages and data.
* **analysis_diversity.R**: This analyses diversity indices for graminoid and forb species
* **analysis_abundance.R**: This analyses cover abundance of *Microlaena stipoides* and *Cynodon dactylon*, total abundance of C~3~ and C~4~ graminoids and C~4~:C~3~ ratios.
* **analysis_LAR.R**: This analyses log annual rates of change in C~3~ and C~4~ using multiple regression with annual soil moisture (Moist), understorey temperature (Temp) and photosynthetic active radiation(PAR).
* **analysis_PRC.R**: This performs principal response curve analysis. The structure of permutation for repeated measurements of nested plots is also defined here.

### Data
* **Table_S2_graminoid_data.csv**: Cover abundance data of graminoid species
* **Table_S3_forb_data.csv**: Cover abundance data of forb species
* **Table_S4_env_data.csv**: Environmental variables (soil moisture, temperature and PAR)
* **Table_S5_graminoid_pfg.csv**: Table of graminoid species and corresponding plant functional types
* **metadata.csv**: Description of the variables in the data above

## Session infomation
The results were generated under the R session as detailed below. 

```{r sessioninfo, echo=FALSE, message=FALSE}
library(plyr)
library(dplyr)
library(ggplot2)
library(lme4)
library(car)
library(lmerTest)
library(vegan)
library(tidyr)
library(lsmeans)
library(visreg)
library(MuMIn)
library(LMERConvenienceFunctions)
sessionInfo()
```

